name: .NET Core

on: [push, pull_request]

jobs:
  test:
    name: Testing
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use .NET Core 3.1.418
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.418
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: 
        dotnet build MathCore.WPF.Styles/MathCore.WPF.Styles.csproj -c Debug --no-restore
        dotnet build Tests/MathCore.WPF.Styles.Tests/MathCore.WPF.Styles.Tests.csproj -c Debug --no-restore
        
    - name: Run Tests
      run: dotnet test Tests/MathCore.WPF.Styles.Tests/MathCore.WPF.Styles.Tests.csproj --no-build --verbosity normal
